const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Rotate,
		C3.Behaviors.Bullet,
		C3.Behaviors.destroy,
		C3.Plugins.Touch,
		C3.Behaviors.MoveTo,
		C3.Plugins.Text,
		C3.Plugins.googleplay,
		C3.Plugins.Touch.Cnds.OnTapGesture,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Exps.layoutheight,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Text.Acts.AddInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Exps.originalviewportwidth,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Exps.originalviewportheight,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{background: 0},
	{life: 0},
	{bulet: 0},
	{Поворот: 0},
	{ship: 0},
	{Пуля: 0},
	{УничтожатьЗаПределамиМакета: 0},
	{Тач: 0},
	{ДвижениеК: 0},
	{enemy: 0},
	{Play: 0},
	{PlayAgain: 0},
	{score: 0},
	{Score: 0},
	{GooglePlay: 0},
	{Life: 0}
];

self.InstanceType = {
	background: class extends self.ISpriteInstance {},
	ship: class extends self.ISpriteInstance {},
	bulet: class extends self.ISpriteInstance {},
	Тач: class extends self.IInstance {},
	enemy: class extends self.ISpriteInstance {},
	Play: class extends self.ITextInstance {},
	PlayAgain: class extends self.ITextInstance {},
	Score: class extends self.ITextInstance {},
	GooglePlay: class extends self.IInstance {}
}